---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  results='hide', 
  fig.align='center', fig.width=8, fig.height=6, fig.retina=2
)
```

```{r}
library(polySimIBD)
```
**Note recombination follows [Figure 1A](https://www.biorxiv.org/content/biorxiv/early/2019/06/18/674440.full.pdf) -- this was our thought but nice figure**


```{r}

k <- 5
rho = 1e-5
pos <- seq(0,1e6,1e5)

sim <- polySimIBD::simulate_IBD_pop_Pedigree(pos = pos, 
                                             rho = rho, 
                                             k = k,
                                             inbreeding = 0
                                             )
  
plot_between_lineages_simulatedpedigree(sim)
plot_within_lineage_simulatedpedigree(sim, lineage = 1)
plot_within_lineage_simulatedpedigree(sim, lineage = 2)

```

#### Between Lineages

```{r, results='asis'}
plot_between_lineages_simulatedpedigree(sim)
```

#### Lineage 1 
```{r, results='asis'}
plot_within_lineage_simulatedpedigree(sim, lineage = 1)
```

#### Lineage 2
```{r, results='asis'}
plot_within_lineage_simulatedpedigree(sim, lineage = 2)
```
