
#.............................
# simhaplo S4 Object
#.............................
setClass("simhaplo", slots = list(haploint = "numeric"))

#.............................
# Structured WF S4 Object
#.............................
setClass("structuredWF", slots = list(WF = "matrix",
                                      demes = "matrix"
                                      ))
