# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sim_swf_cpp <- function(args) {
    .Call(`_polySimIBD_sim_swf_cpp`, args)
}

get_arg_cpp <- function(args) {
    .Call(`_polySimIBD_get_arg_cpp`, args)
}

subset_bvtree_cpp <- function(c, t, m) {
    .Call(`_polySimIBD_subset_bvtree_cpp`, c, t, m)
}

get_bvibd_cpp <- function(args) {
    .Call(`_polySimIBD_get_bvibd_cpp`, args)
}

